# These are merged with the client keywords
# These must always use a list for the keywords
STATIC_KEYWORDS = {
    "coding": [
        "python",
        "programming",
        "tutorial",
        "code",
        "software",
        "develop",
        "java",
        "web",
        "learn",
        "beginners",
    ],
    "graphics": [
        "design",
        "animation",
        "graphics",
        "art",
        "digital",
        "creative",
        "drawing",
        "2D",
        "3D",
        "illustration",
        "sketch",
    ],
    "news": [
        "news",
        "update",
        "breaking",
        "headlines",
        "politics",
        "world",
        "today",
        "reports",
        "latest",
    ],
    "sports": [
        "football",
        "score",
        "highlights",
        "match",
        "vs",
        "sports",
        "cup",
        "race",
        "league",
        "match",
    ],
    "lifestyle": [
        "vlog",
        "tour",
        "mukbang",
        "travel",
        "weekly",
        "daily",
        "vlogging",
        "comedy",
    ],
    "nature": [
        "wild",
        "animals",
        "survival",
        "Scenic",
        "nature",
        "ocean",
        "rainforest",
        "camping",
        "outdoor",
        "tropical",
        "earth", 
        "coastal",
    ],
    "gaming": [
        "gameplay",
        "walkthrough",
        "PC",
        "PS",
        "game",
        "fortnite",
        "xbox",
        "4K",
        "cod",
        "gta",
    ],
    "podcast": [
        "podcast",
        "conversation",
        "interview",
        "Episode",
        "roundtable",
        "disscussion",
        "talkshow",
    ],
    "music": [
        "music", 
        "song", 
        "lyrics"
    ],
    "demo":[
        "repair",
        "guide",
        "how",
        "instructions",
        "unboxing",
        "review",
        "showcase",
        "demo",
        "demonstration",
        "diy",
    ],
}
