services:
  cache-service:
    image: afeefrazick/cache-service
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=$MONGODB_URI
      - VIDEO_ANALYSIS_SERVICE_URI=$VIDEO_ANALYSIS_SERVICE_URI
  video-analysis-service:
    image: afeefrazick/video-analysis-service
    ports:
      - "8000:8000"
    environment:
      - YT_API_KEY=$YT_API_KEY
