name: Cache Service Tests

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "video-analysis-service/**"

jobs:
  build-and-test-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./cache-service

      - name: Run Tests
        run: npm run test
        working-directory: ./cache-service
