name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  Docker_Build_and_Push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: cache-service
            context: cache-service
          - image: video-analysis-service
            context: video-analysis-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}
