name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  Docker_Build_and_Push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: bytesense/cache-service
            dockerfile: cache-service/Dockerfile
          - image: bytesense/video-analysis-service
            dockerfile: video-analysis-service/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}
# jobs:
#   Docker_Build_and_Push:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build Docker Image
#         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bytesense-backend .
#       - name: Push Docker Image
#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bytesense-backend
