name: Video Analysis Service Tests

on:
  push:
    branches: [main, tests-ruff-linting]
    paths-ignore:
      - "cache-service/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "cache-service/**"

jobs:
  build-and-test-video-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./video-analysis-service

      - name: Run tests
        run: python -m unittest discover -s tests
        working-directory: ./video-analysis-service
